---
sidebar: sidebar 
permalink: get-started/intro.html 
keywords: how bluexp operational resiliency works, what is operational resiliency, bluexp 
summary: La resiliencia operativa es un servicio que le ayuda a analizar las alertas y los eventos para mantener el estado, el tiempo de actividad y el rendimiento de los servicios y las soluciones. Mediante el servicio de resiliencia operativa y sus sugerencias automatizadas de solución operativa DE TI, puede implementar soluciones correctivas sugeridas antes de que se produzca una interrupción o un fallo. 
---
= Obtenga más información sobre el servicio de resiliencia operativa
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/concepts/


[role="lead"]
La resiliencia operativa es un servicio que le ayuda a analizar alertas y eventos para mantener el estado, el tiempo de actividad y el rendimiento de los servicios y las soluciones. Mediante el servicio de resiliencia operativa y sus sugerencias automatizadas de solución de riesgos operativos DE TI, puede implementar soluciones correctivas sugeridas antes de que se produzca una interrupción o un fallo.

Este servicio BlueXP implementa soluciones para los clusters de ONTAP de NetApp basadas en la guía NetApp Digital Advisor (anteriormente Active IQ). El servicio detecta vulnerabilidades de seguridad, como problemas de configuración de firmware y software.



== Ventajas del uso del servicio de flexibilidad operativa

El servicio de flexibilidad operativa ofrece las siguientes ventajas:

* Procedimientos automatizados para correcciones en el clúster
* Vista de resumen de la consola que muestra el estado de cada corrección de riesgos
* Registro que permite realizar un seguimiento de las diferentes acciones realizadas




== Qué puede hacer con el servicio de resiliencia operativa

Con el servicio de resiliencia operativa, puede lograr los siguientes objetivos:

* Utilice flujos de trabajo automatizados que le ayudan a detectar riesgos que afectan a su entorno de almacenamiento y emprender acciones para mitigarlos.
* Revisar y actuar sobre recomendaciones operativas, como cuestiones relacionadas con vulnerabilidades de seguridad.




== Coste

NetApp no le cobra por usar el servicio.



== Entornos compatibles

El servicio de resiliencia operativa analiza los clústeres ONTAP de NetApp locales.
