---
sidebar: sidebar 
permalink: get-started/intro.html 
keywords: how bluexp operational resiliency works, what is operational resiliency, bluexp 
summary: La resiliencia operativa de BlueXP es un servicio que te ayuda a analizar alertas y eventos para mantener el estado, el tiempo activo y el rendimiento de los servicios y soluciones. Mediante el servicio de resiliencia operativa y sus sugerencias automatizadas de solución operativa DE TI, puede implementar soluciones correctivas sugeridas antes de que se produzca una interrupción o un fallo. 
---
= Obtenga más información sobre la resiliencia operativa de BlueXP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/concepts/


[role="lead"]
La resiliencia operativa de BlueXP es un servicio que te ayuda a analizar alertas y eventos para mantener el estado, el tiempo activo y el rendimiento de los servicios y las soluciones. Mediante el servicio de resiliencia operativa y sus sugerencias automatizadas de solución de riesgos operativos DE TI, puede implementar soluciones correctivas sugeridas antes de que se produzca una interrupción o un fallo.

Este servicio de BlueXP implementa soluciones para los clústeres de ONTAP de NetApp según las directrices del asesor digital de BlueXP (Active IQ). El servicio detecta vulnerabilidades de seguridad, como problemas de configuración de firmware y software.



== Beneficios de utilizar la resiliencia operativa de BlueXP

La resiliencia operativa de BlueXP ofrece las siguientes ventajas:

* Procedimientos automatizados para correcciones en el clúster
* Vista de resumen de la consola que muestra el estado de cada corrección de riesgos
* Registro que permite realizar un seguimiento de las diferentes acciones realizadas




== Todo lo que puedes hacer con la resiliencia operativa de BlueXP

Con el servicio de resiliencia operativa, puede lograr los siguientes objetivos:

* Utilice flujos de trabajo automatizados que le ayudan a detectar riesgos que afectan a su entorno de almacenamiento y emprender acciones para mitigarlos.
* Revisar y actuar sobre recomendaciones operativas, como cuestiones relacionadas con vulnerabilidades de seguridad.




== Coste

NetApp no le cobra por usar el servicio.



== Entornos compatibles

Análisis de la resiliencia operativa de BlueXP en los clústeres de ONTAP de NetApp en las instalaciones.
