---
sidebar: sidebar 
permalink: get-started/prerequisites.html 
keywords: what are bluexp operational resiliency requirements, economic efficiency prerequisites 
summary: Comience a utilizar la flexibilidad operativa de BlueXP verificando la compatibilidad con su entorno, acceso a la red, inicio de sesión y explorador web. 
---
= Requisitos previos de resiliencia operativa
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Comience verificando la preparación de su entorno operativo, el inicio de sesión, el acceso a la red y el navegador web.

Para utilizar el servicio de resiliencia operativa, debe asegurarse de que su entorno cumple todos los requisitos.

* Su entorno debe cumplir todos los requisitos de BlueXP, incluido un inicio de sesión y acceso a la red desde un navegador Web.
+
Consulte el BlueXP https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-checklist-cm.html["Lista de comprobación de introducción"^].

* El servicio requiere que todos los clústeres estén supervisados por el asesor digital (anteriormente asesor digital de Active IQ). Consulte https://docs.netapp.com/us-en/active-iq/index.html["Documentación de Digital Advisor"^].
* Debe tener credenciales de acceso a los clústeres.
* Aunque no es un requisito, resulta útil que el conector BlueXP esté en su lugar y activado y que se detecte el sistema ONTAP. En caso contrario, el servicio de resiliencia operativa lo guiará por estos procesos.

