---
sidebar: sidebar 
permalink: get-started/prerequisites.html 
keywords: what are bluexp operational resiliency requirements, economic efficiency prerequisites 
summary: Empiece a utilizar el servicio de resiliencia operativa BlueXP verificando la compatibilidad con su entorno, acceso a la red, inicio de sesión y explorador web. 
---
= Requisitos previos para la resiliencia operativa de BlueXP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Comience verificando la preparación de su entorno operativo, el inicio de sesión, el acceso a la red y el navegador web.

Para usar el servicio de resiliencia operativa, debe asegurarse de que su entorno cumpla con todos los requisitos.

* Su entorno debe cumplir todos los requisitos de BlueXP, incluido un inicio de sesión y acceso a la red desde un navegador Web.
+
Consulte la https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-standard-mode.html["Inicio rápido de BlueXP"^] y.. https://docs.netapp.com/us-en/bluexp-setup-admin/reference-networking-saas-console.html["Información de red de BlueXP"^].

* El servicio requiere que todos los clústeres estén supervisados por el asesor digital de BlueXP (Active IQ), que requiere que esté habilitado AutoSupport en el activo. Consulte https://docs.netapp.com/us-en/active-iq/index.html["Documentación del asesor digital de BlueXP"^].
* Debe tener credenciales de acceso a los clústeres.
* Para llevar a cabo una corrección automática, se necesita un conector BlueXP. Resulta útil si el conector BlueXP está en su lugar y habilitado y el sistema ONTAP se detecta antes de iniciar la corrección mediante la resiliencia operativa de BlueXP. Si el conector no está en su lugar, el servicio de resistencia operativa le guiará a través de esos procesos. Si en lugar de eso corrige el uso de un archivo Ansible, no es necesario el conector BlueXP.

